### ISSUE TITLE
Entity sensors not found

### ISSUE THREAD

**Issue by djbr22** [vaparr/ha-overseerr#7]
Hello,

I'm in the process of setting this up. I have added it through HACS and I can see the 3 services, however I don't see any new sensors created. In the logs, I see this:

![image](https://user-images.githubusercontent.com/5007649/127729560-7599e52c-0585-4f50-a176-3af0437b4d6a.png)

Which makes sense as to why when I call the service using the code below to download something from Overseerr, it just shows "unknown".
```
service: overseerr.submit_tv_request
data:
  name: breaking bad
  season: latest

```

On Overseerr version v1.25.0
